### ISSUE TITLE
Wrong package address for Laravel helpers in Helo app.

### ISSUE THREAD

**Issue by CraftLogan** [beyondcode/helo-community#1]
You currently have composer require beyondcode/laravel-helo

<img width="882" alt="Screen Shot 2020-04-20 at 9 12 12 PM" src="https://user-images.githubusercontent.com/10950466/79814304-e40c0400-834b-11ea-8076-51fc298602b1.png">

and it should be composer require beyondcode/helo-laravel

-Logan

**Comment by sschlein** [comment]
Whoops, I just fixed it and we'll likely release a 1.0.1 before we announce HELO later today. Thanks!
