### ISSUE TITLE
Can't change from/to email addresses when forwarding...

### ISSUE THREAD

**Issue by rhukster** [beyondcode/helo-community#11]
The `from` and `to` fields are editable, so it appears you can choose the `from` and the `to`, but it seems the ORIGINAL email's `from` and `to` are always used.  

This is confusing and somewhat limiting when testing an email with predefined `from` and `to` fields. I want to forward it to a real account so I can see how it looks in a specific client.

**Comment by robclancy** [comment]
The forwarding wasn't even working for me yesterday. Now trying I see this same issue. Feels like forwarding was a last minute feature that was barely tested. And it's the main feature I got this for, everything else I can do easily with other options.

**Comment by sschlein** [comment]
@robclancy bold statement, happy to give you a refund at support@beyondco.de if you don't like the app.

The other option is to let us monitor the issues that people have in the first days and release a new version that addresses them 🙂

**Comment by CJau777** [comment]
I seem to be having trouble forwarding messages too.  Was unable to authenticate with Google, but using another SMTP server I was and get an error that no recipients are defined.

Is there any further info I can provide to help try diagnose?

<img width="873" alt="Screen Shot 2020-05-04 at 12 47 08 pm" src="https://user-images.githubusercontent.com/25449733/80940198-2cccbe00-8e1e-11ea-861b-53114677cc54.png">

**Comment by robclancy** [comment]
> @robclancy bold statement, happy to give you a refund at support@beyondco.de if you don't like the app.
> 
> The other option is to let us monitor the issues that people have in the first days and release a new version that addresses them slightly_smiling_face

40 days?

**Comment by robclancy** [comment]
> The other option is to let us monitor the issues that people have in the first days and release a new version that addresses them slightly_smiling_face

Posted 83 days ago. This advertised feature is still not working. 

https://github.com/beyondcode/helo-community/issues/17
This bug still not addressed, just asking for a screenshot to show something invisible.

Is that refund from your condescending comment still on offer?

**Comment by sschlein** [comment]
Yes, if these things are that crucial for you, please send an email and I'll give you a refund and disable the license.

**Comment by hcancelik** [comment]
@sschlein Will there be a fix for this issue?

**Comment by mechelon** [comment]
Will be fixed in the next release.
