### ISSUE TITLE
Mails with attachments and maybe bccs affect snappiness of app

### ISSUE THREAD

**Issue by manogi** [beyondcode/helo-community#12]
Hi there, thanks for HELO. It is so great, and I'm really happy with it.
Just a small thing: the response time of the app to clicks seems to suffer from certain kind of mails.

Im on version 1.0.2.

To start, I have two mail boxes with 2 mails in each. The mails in one mail box have a small csv file attachment. 

Clicking around in my mail boxes (switching mails, switching mail boxes) ist quick and snappy.

Now I send a mail that has a 600 kb attachment. The clicking around is less snappy (the lag is way less than a second still - but noticeable).

I remove that mail (the lag is gone) and send the same mail with a bcc. The lag is a bit longer - but under a second.

Now I go wild and send the same mail again twice. The lag grows to around a second.

I definitely could live with this, there is no need to have mail boxes full of mails anyway, but of course the experience would be even nicer if the app stayed snappy. Also it affects clicking around in all mail boxes - not just the one with the mails causing it.

Best regards and keep up the great work!

**Comment by sschlein** [comment]
Thank you for your detailed guide to create the issue on our end. We are currently collecting these issues and want to address them early next week.

**Comment by fridzema** [comment]
<img width="993" alt="Screen Shot 2020-04-23 at 16 07 36" src="https://user-images.githubusercontent.com/8180660/80108502-a80bb580-857c-11ea-828f-22c3128731c6.png">

This is what happened to me if i send emails with attachments.

**Comment by manogi** [comment]
@fridzema I am not sure we are having the same issue - when I talk about sending mails with attachments I mean sending from my app - the mails turn up in HELO quite OK. Maybe you need to create a new issue and explain it a bit more in detail.

**Comment by euneuber** [comment]
I can confirm:

- Emails with large attachments slow HELO down...
- Having more than 200 emails in a mailbox slows HELO down...
- Having a sender sending small emails every minute slows HELO down...

**Comment by mpociot** [comment]
I already have a fix for this working locally. Let me test this a bit more, and then I’ll roll it out soon :)

**Comment by mpociot** [comment]
This is now fixed in version 1.1.0
