### ISSUE TITLE
Delete a Mailbox form list of mailboxes

### ISSUE THREAD

**Issue by euneuber** [beyondcode/helo-community#17]
Hi,
Your tool is very helpful, but I guess you never imagined how it can be used... ;-)

I got several 1000s email from a postfix service delivered... now I'd like to delete them with one click. This can be done (right click menu) in the header of the mailbox when opened.

But to open a mailbox this 1000s of mails takes time -- maybe you can add the `delete` action to the list of mailboxes as a little trash can?

**Comment by SamuelNitsche** [comment]
You can delete whole mailboxes on the mailbox overview by right clicking on it.

**Comment by euneuber** [comment]
Strange, right click on the mailbox in the mailbox overview does not open a context menu for me (1.0.2)

**Comment by SamuelNitsche** [comment]
This is really strange. Works perfectly fine for me in 1.0.2

<img width="420" alt="Bildschirmfoto 2020-04-28 um 13 23 14" src="https://user-images.githubusercontent.com/24483576/80481905-9d259c00-8953-11ea-8e5e-d31fbbd253e2.png">

**Comment by euneuber** [comment]
I did upgrade to version 1.1.0 -- unfortunately not working...

Did I ever mention that a I use Linux?

**Comment by mpociot** [comment]
Could you explain what "not working" means? Do you have the context menu but clicking it doesn't do anything?

**Comment by euneuber** [comment]
No context menu on right click.

**Comment by themightychris** [comment]
I'm on Linux too with latest build, it's hard to get the context menu open, and when I do the only item in it is "Copy Link". It kinda feels like two context menus are fighting as I see a smaller box animate first that looks fit for "Delete" and then the copy link menu pops on top (if i'm lucky, most right clicks just flash the animation for a moment)

**Comment by sschlein** [comment]
Can someone add a screenshot for this? Which Linux distributions do you use?

**Comment by robclancy** [comment]
I don't understand why you need a screenshot of it not showing? 
https://i.imgur.com/aV0C4Fb.png

**Comment by sschlein** [comment]
Just tested on plain Ubuntu 18.08 with standard GUI and can confirm that the context menus are fighting in some way. That also means that we are able to debug it now.

**Comment by hellozach** [comment]
I am having this issue on Windows 10 as well. Sometimes I will see the context menu for less than a second, but there doesn't seem to be a pattern to when I will see it.

**Comment by timrspratt** [comment]
Would a "delete all" button inside the mailboxes themselves, be better suited for a use case with 1,000+ emails per box? I know it's the same as deleting an inbox, but it feels more intuitive than removing the inbox and dealing with the mailbox list (btw is that alphabetically ordered? If not the mailboxes would shift position which might be important to people for muscle memory for a specific box location in the list)

**Comment by sschlein** [comment]
I have added a delete all button and a bulk delete operation. This will be released with 1.2 shortly
