### ISSUE TITLE
Error in Laravel queue mail

### ISSUE THREAD

**Issue by azurinspire** [beyondcode/helo-community#2]
In Laravel code like:

```php
Mail::to($recipient)->queue(new SomeMail($email));
```

is giving error:

```
Argument 1 passed to Illuminate\Mail\SendQueuedMailable::handle() must implement interface Illuminate\Contracts\Mail\Factory, instance of BeyondCode\HeloLaravel\Mailer given
```

Steps to reproduce:

```shell
laravel new helo
cd helo
php artisan make:mail TestMail
touch resources/views/test.blade.php
composer require beyondcode/helo-laravel
```

Change TestMail.php to use `test` as a view and open Tinker:

```
Mail::to('test@test.com')->queue(new TestMail())
```

**Comment by msnegurski** [comment]
I have same mistake in fresh laravel app with auth scaffolding when sending emails for email verificatio and password resets

**Comment by cvallejo** [comment]
I have the same issue when I try to send a confirmation email to the user.

If I try to use `php artisan helo:test`all works fine, but if I click on resend the email, the system fails:

```TypeError
Argument 1 passed to Illuminate\Notifications\Channels\MailChannel::__construct() must implement interface Illuminate\Contracts\Mail\Factory, instance of BeyondCode\HeloLaravel\Mailer given
```

**Comment by azurinspire** [comment]
This issue is already in proress on helo-laravel project

beyondcode/helo-laravel/issues/1
