### ISSUE TITLE
Missing remote SMTP functionality

### ISSUE THREAD

**Issue by elbsurfer** [beyondcode/helo-community#22]
Hello,
in order to use HELO as a dummy inbox on staging websites it would be nice to have a remote smtp server that I can use in my application. The email address "xxxxxx-xxx-xxx-xxx-xxxx@usehelo.cloud" does not help in this case.

Do you have this functionality on your list?

**Comment by sschlein** [comment]
Hey @elbsurfer,

That's beyond our current scope of HELO. This might change in the future, so don't take it as a "no" forever but we don't have it on the roadmap yet.
