### ISSUE TITLE
multiple quality of life improvements, arrow keys, delete default behaviour, keyboard shortcuts

### ISSUE THREAD

**Issue by vesper8** [beyondcode/helo-community#23]
I've been using HELO more and more and am finding small things that I wish were there.

When browsing received emails, currently using the up/down arrow keys scrolls the left pane, I would prefer if the up/down arrow keys actually went from one email to the next so I can easily view multiple emails without using the mouse

Also, currently, when deleting any email (by selecting it and then clicking on the delete button) the default behaviour is that it focuses on the last received one, instead, it should focus on the one nearest the one you just deleted.

As well, I wish it was possible to delete emails using the keyboard, either DEL or CMD-DEL

Also, I don't currently see a way to delete multiple emails at once by selecting multiple using the shift key or selecting checkboxes, or simply a 'clear all' button, although I prefer to have both. Sometimes I want to delete multiple emails at once easily and quickly but not clear them all. It would be also nice to be able to mark certain emails as 'starred' so they are not deleted when performing a 'clear all'

**Comment by sschlein** [comment]
Hey,

these are all great suggestions! We are currently still in the phase of monitoring for bugs to iron them out as quickly as possible – but plan to work on a quality-of-life version with user feedback after that. So I don't have an ETA on this yet but think that all your suggestions will find their way into the app =)

**Comment by unansweredocd** [comment]
Do you guys plan on sharing a roadmap in the future? That would be awesome.

**Comment by vesper8** [comment]
@sschlein it's been months and I haven't seen many QoL improvements.. I would imagine you're out of the bug fixing phase now. Is there a roadmap for when you'll be bringing more improvements to the Developer Experience? Would love to see some of my "great" suggestions added in. Thanks

**Comment by mechelon** [comment]
This will be integrated in one of the next releases.
