### ISSUE TITLE
Add ability to see SMTP transcript

### ISSUE THREAD

**Issue by Synchro** [beyondcode/helo-community#24]
At present messages sent to HELO simply appear in a mailbox if they are successfully delivered, but if the delivery fails, you have no way of seeing it from the HELO end, for example, [if you did not configure authentication](#3). In situations like this, it would be useful to be able to see the low-level SMTP activity that HELO is using. For example, this is is how it's displayed in the open-source ['fakeSMTP' Java app](http://nilhcem.com/FakeSMTP/):

```
09:41:07 AM - SMTP server *:2500 started
09:41:12 AM - SMTP connection from localhost/0:0:0:0:0:0:0:1, new connection count: 1
09:41:12 AM - Server: 220 octoo.local ESMTP SubEthaSMTP null
09:41:12 AM - Client: EHLO [127.0.0.1]
09:41:12 AM - Server: 250-octoo.local
250-8BITMIME
250-AUTH LOGIN
250 Ok
09:41:12 AM - Client: AUTH LOGIN
09:41:12 AM - Server: 334 VXNlcm5hbWU6
09:41:12 AM - Server: 334 UGFzc3dvcmQ6
09:41:12 AM - Server: 235 Authentication successful.
09:41:12 AM - Client: MAIL FROM:<webmaster@example.com>
09:41:12 AM - Server: 250 Ok
09:41:12 AM - Client: RCPT TO:<marcus@example.com>
09:41:12 AM - Server: 250 Ok
09:41:12 AM - Client: DATA
09:41:12 AM - Server: 354 End data with <CR><LF>.<CR><LF>
09:41:12 AM - Server: 250 Ok
09:41:12 AM - Client: QUIT
09:41:12 AM - Server: 221 Bye
```

Note that this fake server doesn't show responses to auth commands, and omits the content of the DATA command. I don't see any good reason to omit those given that this is most often used in debugging contexts where you do need to see low-level data.

**Comment by mpociot** [comment]
I'm going to close this issue, as I don't think it's something that we will add anytime soon. If more people request this feature, we might look back into it.
