### ISSUE TITLE
Select multiple emails

### ISSUE THREAD

**Issue by paulhennell** [beyondcode/helo-community#25]
Currently there seems to be no way to select multiple emails in an inbox for a batch operations.
If you have many similar emails with conditional logic you wanted to check in the inbox it would be useful to be able to select multiple emails and then right click -> delete to remove the ones you've dealt with. 

Multi-select should work as typical file explorer standards:
- Cmd/ctrl click email = add to selection
- Shift + click email = continuous selection

My personal requirement is just for deleting multiple selected messages as a batch. A similar batch share or batch forward operation may also be handy for some users.

**Comment by turbo124** [comment]
came here for this, as someone who likes to keep a clean inbox, having thousands of dev emails that i need to manually delete individually messes with my OCD :)

**Comment by timrspratt** [comment]
👍 it feels like bulk actions should sit where the share button is, so that you can delete multiple emails using the same technique as share is currently doing

**Comment by sschlein** [comment]
Bulk delete for multiple emails and whole inboxes is built and will be released in version 1.2 shortly
