### ISSUE TITLE
Expected response code 220 but got an empty response

### ISSUE THREAD

**Issue by ultimateBusiness** [beyondcode/helo-community#26]
I have made a fresh installation of Laravel 7 with Auth and setup as shown in the picture

<img width="2029" alt="Bildschirmfoto 2020-05-01 um 14 57 05" src="https://user-images.githubusercontent.com/1951575/80810999-5212bf80-8bc5-11ea-9c92-498a056d0cd7.png">

When I request a password-reset and send the form I get the following error with also an error-message showing up in HELO "write EADDRNOTAVAIL"

<img width="2417" alt="Bildschirmfoto 2020-05-01 um 15 06 12" src="https://user-images.githubusercontent.com/1951575/80811035-60f97200-8bc5-11ea-94bc-fce0d5738c67.png">

All running on a Mac with standard Laravel Valet installed.

**Comment by SamuelNitsche** [comment]
I think you have to specify the sender address in your `.env` file.

**Comment by ultimateBusiness** [comment]
Sorry, but this doesn't work - same error-message as before ;-(

**Comment by mpociot** [comment]
Can you try and change the port? It seems like port 2525 is already taken on your mac.

**Comment by ultimateBusiness** [comment]
I have tried it with another port (2727) but the result is the same.

I also have validated with a portscan that before starting HELO p2525 is not in use and after starting it is.

**Comment by sschlein** [comment]
@ultimateBusiness Did you resolve the issue or still waiting for a solution? It doesn't seem to be a common issue and so I guess it's somehow related to your machine.

**Comment by sschlein** [comment]
Closed due to inactivity
