### ISSUE TITLE
Cannot get it work with Rails

### ISSUE THREAD

**Issue by hcancelik** [beyondcode/helo-community#29]
```
config.action_mailer.delivery_method = :smtp
config.action_mailer.smtp_settings = {
  :user_name => 'Test',
  :password => '',
  :address => '127.0.0.1',
  :domain => '127.0.0.1',
  :port => '2525',
  :authentication => :cram_md5
}
```

I have this config in my development environment but cannot get any emails sent to Helo. If I replace the config with mailtrap account information it works fine.

Helo works with my Laravel setup so I'm guessing the issue with Helo with Rails.

**Comment by sschlein** [comment]
Can you remove the authentication and try again? I have no direct experience with Rails but this was an issue with another config, too.

**Comment by hcancelik** [comment]
> Can you remove the authentication and try again? I have no direct experience with Rails but this was an issue with another config, too.

It worked. Thanks a lot for a quick response and a solution 😄

**Comment by sschlein** [comment]
I run into the issue myself with a Laravel project during the development phase 😅

I fixed it for Rails in the docs and it will be fixed in the app internal docs with the next release:
https://docs.beyondco.de/helo/1.0/getting-started/configuration.html#ruby-on-rails
