### ISSUE TITLE
Add option to turn off authentication

### ISSUE THREAD

**Issue by Synchro** [beyondcode/helo-community#3]
HELO allows anyone to connect and doesn't use the username and password for anything – but they are still required. Attempting to issue a `MAIL FROM` without a prior `AUTH` fails:

```
2020-04-21 12:06:28	SERVER -> CLIENT: 220 Octoo.local ESMTP
2020-04-21 12:06:28	CLIENT -> SERVER: EHLO Octoo.local
2020-04-21 12:06:28	SERVER -> CLIENT: 250-Octoo.local Nice to meet you, [::1]
                   	                  250-PIPELINING
                   	                  250-8BITMIME
                   	                  250-SMTPUTF8
                   	                  250 AUTH LOGIN PLAIN
2020-04-21 12:06:28	CLIENT -> SERVER: MAIL FROM:<user@example.com>
2020-04-21 12:06:28	SERVER -> CLIENT: 530 Error: authentication Required
2020-04-21 12:06:28	SMTP ERROR: MAIL FROM command failed: 530 Error: authentication Required
```

It would be useful to be able to disable this authentication requirement. It's entirely normal to not require authentication when submitting to localhost or other allow-listed sources; for example, GoDaddy's mail servers do this. This would also apply if HELO was used via PHP's `mail()` function configured to relay the connection via a local sendmail binary (the usual configuration).

**Comment by ramzy11** [comment]
Hi,
I have the same problem when configuring docker and sendmail. Authentification is required. 
Here is my config : 
`sendmail_path = "/opt/go/bin/mhsendmail --smtp-addr='host.docker.internal:2525'"`
It would be very useful if we can disable it.

**Comment by mpociot** [comment]
The username is used as a mailbox name in HELO - maybe we could make it optional and move everything into a "Default" mailbox in case it's not specified

**Comment by Synchro** [comment]
That sounds good.

**Comment by Cazzar** [comment]
I might document this here to help others, I have managed to work around it for PHP's `mail()` function by setting the following INI settings:

```
sendmail_path = "/usr/local/bin/msmtp -f test@test.com test@test"
mail.force_extra_parameters = "--host=127.0.0.1 --port 2525 --auth=plain --user=PHP-Sendmail --passwordeval=echo"
```

**Comment by mechelon** [comment]
Will be added in the next release.
