### ISSUE TITLE
Cant use port 2525

### ISSUE THREAD

**Issue by zaherg** [beyondcode/helo-community#31]
Since upgrading to version (1.1.1), I faced this problem; the app will always complain that another application is using port 2525.

![image](https://user-images.githubusercontent.com/27624/81789219-549ddf00-950c-11ea-868a-1aaffa4724ca.png)

meanwhile, if I checked, I can see that HELO is the one who uses it

![image](https://user-images.githubusercontent.com/27624/81789291-6e3f2680-950c-11ea-9ff9-45c5e2375313.png)

Also, if I changed the port, the start button won't work, and I'll have to restart the application so it pick up the new port.

**Comment by zaherg** [comment]
I guess it will be fixed next release.

**Comment by sschlein** [comment]
Reopen that we don't forget it :-)

I have this issue sometimes too – but it seems to be a display issue because I still get emails from my local environments in HELO.

**Comment by zaherg** [comment]
In my case I was not able to receive any email until I changed the port and
restart the app.

**Comment by zaherg** [comment]
@sschlein any update about this? 
I am facing the issue from time to time, and when I change the port and click start nothing work https://d.pr/v/AZuAzz I need to restart the app so it can pick up the new port

**Comment by sschlein** [comment]
@zaherg We finally launched our new website (https://beyondco.de) yesterday. We are starting to work on new releases of HELO and Tinkerwell that address bugs now.

**Comment by warrickbayman** [comment]
I have the same issue. Seems to happen if you close the window by clicking the close button (on Mac) and click the HELO icon in the dock to bring it back up again. Then I get "port 2525 is in use" and I have kill the app properly and relaunch. As long as I don't close the HELO window, all seems fine.

**Comment by zaherg** [comment]
@warrickbayman can you also confirm this behavior:

>update: something I noticed is that the app will work as long as I don't open the settings page, once I open the settings page things will get messy and the app will behave strangely.

**Comment by warrickbayman** [comment]
@zaherg App works fine even with the "port 2525 is in use" message and the settings page open. As long as the HELO window is open, it receives messages. As soon as I close the window, it stops working.

**Comment by zaherg** [comment]
@warrickbayman Ah I noticed that, basically whenever the app is spinning a new window after you have closed the main one, it stop working. that's explain a lot.

@sschlein I think this info will help fixing the issue
