### ISSUE TITLE
Docs say to use `:port:` but I had to use 2525

### ISSUE THREAD

**Issue by edalzell** [beyondcode/helo-community#33]
In the docs for Laravel, it says to use `MAIL_PORT=:port:`
![image](https://user-images.githubusercontent.com/6069653/83052895-cc880100-a004-11ea-8ff5-bad9b68429e0.png)

But I needed to use port 2525 to get it to work. I am on L5.8

Did I do something wrong? Doc issue? Code issue?

**Comment by sschlein** [comment]
Seems like we copy and pasted this from the app where :port: gets replaced by 2525 or the actual port that you use in the app. Will fix it shortly, thanks for letting us know!

**Comment by sschlein** [comment]
https://beyondco.de/docs/helo/getting-started/configuration =)
