### ISSUE TITLE
Links checking / Links trigger actions?

### ISSUE THREAD

**Issue by R00118189** [beyondcode/helo-community#34]
Could you confirm the link checking feature actually triggers actions of those links?
I noticed with our unsubscribe link, users are being unsubscribed if sent to HELO (of course if send with log driver the link is not triggered). 

Maybe we could have feature to disable link checking if this is the case.

**Comment by mpociot** [comment]
Hi!

Yeah, the link checker tries to perform a HEAD request to the URL. If this fails, an actual GET request will be sent.
You can already disable the link checker in the settings if you want to prevent this from happening.
You will still see a list of all links, but there won't be a status code associated.
