### ISSUE TITLE
Header Data and Attachments Missing

### ISSUE THREAD

**Issue by hellozach** [beyondcode/helo-community#35]
If the `Date` header is not set in the email, then the header information (subject, to, from, message ID, etc) and Attachments don't show at the top. Also, all emails listed in the left that don't have a Date header set remain blue.

Note, if the previous email being looked at has a Date field then that email's header stays showing. It seems like data isn't being cleared out when switching to an email without a Date field.

**Comment by sschlein** [comment]
Is this common that emails don't have a date field?

**Comment by sschlein** [comment]
Closed because of inactivity
