### ISSUE TITLE
Symfony OpenSSL TLS error

### ISSUE THREAD

**Issue by geraintp** [beyondcode/helo-community#36]
When using the suggested config for Symfony an open SSL error is triggered that crashes the mailserver.

<img width="1060" alt="Screenshot 2020-06-09 at 15 23 27" src="https://user-images.githubusercontent.com/1032357/84159708-45577600-aa65-11ea-9d24-ef23849c6d30.png">

<img width="1324" alt="Screenshot 2020-06-09 at 15 23 38" src="https://user-images.githubusercontent.com/1032357/84159724-48eafd00-aa65-11ea-8cf8-20afcee4c48b.png">

Symfony 4.4.8
Helo 1.1.1

**Comment by craftyshaun** [comment]
See #32 I had the same issue when trying to use TLS when I had Laravel misconfigured.

 I don't think HELO supports TLS. Try with no encryption as per the Laravel Docs.

**Comment by sschlein** [comment]
Yes, HELO does not support TLS and you have to remove the encryption from the connection. I'll update this in the docs shortly.

**Comment by sschlein** [comment]
https://beyondco.de/docs/helo/getting-started/configuration#symfony
