### ISSUE TITLE
Windows App Constantly Freezing and Really Slow

### ISSUE THREAD

**Issue by JeffreyHosler** [beyondcode/helo-community#37]
It worked fine at first. But then I sent a test email to 1000 address and now nothing will load. When the sidebar does decide to load and I click on an email, it takes several minutes to load the email, meanwhile the app is frozen until it loads. 

![Capture](https://user-images.githubusercontent.com/19713544/84389932-d3963e00-abc4-11ea-8325-3643d06ca381.PNG)

**Comment by sschlein** [comment]
Sorry for the late reply, we are just catching up.

We add a button to purge all email inboxes in the settings to resolve this issue in the future. In the meantime, you can do this manually by going to the folder that stores your data for HELO:

https://beyondco.de/docs/helo/troubleshooting/common-issues#paths
