### ISSUE TITLE
Not working with Homestead on Mac

### ISSUE THREAD

**Issue by henryavila** [beyondcode/helo-community#38]
Ehen using on Mac with Homestead, I always get the error:
`Connection could not be established with host 10.0.2.2 :stream_socket_client(): unable to connect to 10.0.2.2:2525 (Connection timed out)`

**Comment by sschlein** [comment]
Are HELO and the SMTP server running (validate on settings page)?

Could you post the related parts of your homestead.yaml and email configuration?

**Comment by henryavila** [comment]
Hi @sschlein,

The SMTP server is running on port 2525


My .env contain
```
MAIL_MAILER=smtp
MAIL_HOST=10.0.2.2
MAIL_PORT=2525
MAIL_USERNAME=Inbox-Name
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```

The Helo setting page, say explicitly to use the ip 10.0.2.2 if using Homestead.

My Homestead.yaml file contain just the default config. I believe there`s nothing related to it, or there's some Homestead config I must care?

**Comment by keenminded** [comment]
@henryavila Hope you got this resolved by now, but I am using the same exact configuration with Homestead and can confirm that it is functioning as documented.

**Comment by sschlein** [comment]
@henryavila Did you resolve this issue? If yes, can you tell me how we can improve the docs so that we can make this easier for others?

I'm closing the issue for now, but would re-open it if it does not work yet.

**Comment by addidesign** [comment]
Hi @sschlein I'm getting the same error as above - is this a known issue? 

`local.ERROR: Connection could not be established with host 10.0.2.2 :stream_socket_client(): unable to connect to 10.0.2.2:2525 (Operation timed out) {"exception":"[object] (Swift_TransportException(code: 0): Connection could not be established with host 10.0.2.2 :stream_socket_client(): unable to connect to 10.0.2.2:2525`

Cleared config etc, Homestead 9.6.0, Laravel  8.58.0, Mac 11.5.1
