### ISSUE TITLE
Application grinds to a halt on mass mailings

### ISSUE THREAD

**Issue by unansweredocd** [beyondcode/helo-community#39]
Hey,

I just started using this. Was planning on using it with our newsletter system so I can test mass mailings and throttling. What I noticed rather quickly was that the application basically stopped responding after a given amount of e-mails.

I'm trying to send 8040 e-mails, throttled in a way where we're sending 4 mails per second. Can you let me know if you guys plan to support this type of behaviour in the future?

**Comment by sschlein** [comment]
Why would you send 8000 emails to a testing application?

In short: no

**Comment by unansweredocd** [comment]
Good point. The reasoning behind it is that I figured I would see whether Redis throttling was working properly. I had a bit of an issue with duplicating jobs which is not a very fun experience when you're sending e-mails.

Anyhow, I'll close the issue since I totally understand the reasoning behind what you just said. Thanks for the quick reply :)

**Comment by sschlein** [comment]
You can delete these emails if you delete the data of HELO and start from scratch:

https://beyondco.de/docs/helo/troubleshooting/common-issues#paths

We want to add a button that purges all emails in the settings that the rest of your configuration keeps intact, but I don't have an ETA yet.
