### ISSUE TITLE
In email preview - links are broken

### ISSUE THREAD

**Issue by ModestasV** [beyondcode/helo-community#4]
**Version**: 1.0.2 - Linux edition
**Issue\Feature request**: Issue
**Laravel version**: 7.6.2
**Mail template core**: `markdown`
**Main problem**: When email is received with a link - preview links are broken. Link checker is fine.
**Description**:
Email is sent via Laravel markdown editor and contains a button component. That button component has link to the application which is not displayed correctly/missing. Raw text shows this:

```
<a href=3D"" class=3D"button b=
utton-primary" target=3D"_blank" rel=3D"noopener" style=3D"box-sizing: bord=
er-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,=
 Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Sego=
e UI Symbol'; position: relative; -webkit-text-size-adjust: none; border-ra=
dius: 4px; color: #fff; display: inline-block; overflow: hidden; text-decor=
ation: none; background-color: #2d3748; border-bottom: 8px solid #2d3748; b=
order-left: 18px solid #2d3748; border-right: 18px solid #2d3748; border-to=
p: 8px solid #2d3748;">Create password</a>
```

Call in markdown looks like this:

```
@component('mail::button', ['url' => $url])
    Create password
@endcomponent
```

---

This issue was not reproduced while using a different mail provider nor sending emails to live inbox.

**Comment by mpociot** [comment]
That's really weird, as HELO does not manipulate the incoming email text. The raw email is already missing that URL. Are you sure that the URL was properly passed to the mailable?

**Comment by ModestasV** [comment]
I forgot to add screenshots... So sorry!

But on the bright side - I've updated to 1.1.0 and the issue seems to be gone. Last time I had links set correctly and all of them were read in the links tab. If I click it there - it takes me where I needed but the button wasn't taking it :(

I suppose this can be closed. If I'll see it again - will re-open.
