### ISSUE TITLE
HELO - Application won't quit

### ISSUE THREAD

**Issue by vmitchell85** [beyondcode/helo-community#41]
**HELO Version:** Version 1.1.2 (1.1.2)
**MacOS Version:** 10.15.5 (19F101)

When trying to quit using ⌘Q or the application menu the window closes but HELO is still open.

**Comment by Cannonb4ll** [comment]
Having the same issue here.

**Comment by Glennmen** [comment]
Same issue here too after updating to 1.1.2

**Comment by sschlein** [comment]
Looks like we are going to release an update next week. That's an interesting but annoying bug.

**Comment by sschlein** [comment]
Fixed with 1.1.3 (released a few minutes ago)
