### ISSUE TITLE
Installation via Homebrew cask

### ISSUE THREAD

**Issue by rawilk** [beyondcode/helo-community#42]
Would it be possible to create a homebrew cask for this to allow installation through homebrew like you can with Tinkerwell? It's not really a huge deal, but it would be nice to just be able to add helo as well to a brewfile so it can be installed along with the rest of my apps on a new machine setup or macos reinstall.

**Comment by sschlein** [comment]
This was already tried by @owenvoke at https://github.com/Homebrew/homebrew-cask/pull/81062 but got rejected because we have downloads directly from DigitalOcean spaces without a specific subdomain.

**Comment by sschlein** [comment]
I also added an additional comment at the PR and created a proper subdomain for the download so that this should be available/possible soon
