### ISSUE TITLE
Icon broken in applications folder

### ISSUE THREAD

**Issue by unansweredocd** [beyondcode/helo-community#46]
Hey,

I'm on MacOS. The application icon seems to be broken when I look at in the applications folder. Icon is fine in the dock and Alfred, just seems to be this location that has the issue.

![Screenshot 2020-08-13 at 11 22 35](https://user-images.githubusercontent.com/68014739/90117523-59666f00-dd57-11ea-894f-2ca7a241c73e.png)

**Comment by sschlein** [comment]
Can you confirm that this happens with the latest version 1.1.4?

I thought I have fixed this but seems to be still broken.

**Comment by unansweredocd** [comment]
I can confirm it's happening on 1.1.4.

**Comment by sschlein** [comment]
Ok thanks, we'll fix this with the next release :)

**Comment by unansweredocd** [comment]
My hero.

**Comment by sschlein** [comment]
Which macOS version is this? I have an icon in my applications folder for 10.15.5

**Comment by unansweredocd** [comment]
10.15.6

**Comment by martyf** [comment]
FWIW, I'm on 10.15.6 and have the icon appearing correctly in the Dock and Applications folder.

In the past I have had macOS corrupt icons in the Dock, and have used terminal commands to clear the icon cache, but admittedly has been a long time since that's happened to me. I've never had it happen in a Finder window either.

**Comment by sschlein** [comment]
1.1.3 had a corrupt one too – maybe this is some way of macOS cache?

**Comment by unansweredocd** [comment]
Sure seems like it. Can't seem to find a way to properly clean those out. Trying this for now, https://apple.stackexchange.com/questions/183166/how-do-i-restore-icons-in-finder will report back.

**Comment by unansweredocd** [comment]
Clearing cache with the above doesn't seem to work. But as others don't seem to have the issue I'm pretty sure it's just an issue with my machine (Mac mini from 2014). 

I'll go ahead and close the issue, as you guys can't do anything about this (I think).

**Comment by sschlein** [comment]
You can try to delete the app from the application folder and download and install the latest version again. Maybe this fixes it already.

**Comment by unansweredocd** [comment]
Tried that too, didn't fix it.
