### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by daugaard47** [beyondcode/helo-community#47]
I receive the message, 

> HELO is ready to update. Please quit the app and restart it to trigger the update process

So I quit, wait a few minutes and restart. No update and receive the same update message again.

Not a huge issue. End up going to the site and downloading the latest version. Is there something I need to do to make the auto-update feature work. 

- On windows 10

**Comment by sschlein** [comment]
Really strange – I got additional support requests with the same issue. We are going to look into this for the upcoming update.

**Comment by RhysLees** [comment]
Still getting this now
