### ISSUE TITLE
clear image cache ?

### ISSUE THREAD

**Issue by vesper8** [beyondcode/helo-community#48]
My emails use images that are stored on a server somewhere, such as for the logo. I updated the logo image and if I browse to the URL of the logo it shows the new logo. But when sending emails to Helo it still shows the old logo. The name and url is the same. Normally if I had an issue like this in Chrome I would clear cache or perform a hard reload and it would start to show the new image. But how to do this in HELO ?

**Comment by sschlein** [comment]
@vesper8 Can you check if this works? https://stackoverflow.com/questions/31446782/how-to-clear-the-cache-data-in-electronatom-shell

If yes, I'll add this to the docs (and create a button in the settings to clear the HELO cache in an upcoming version)

**Comment by mechelon** [comment]
Will be fixed in the next release.
