### ISSUE TITLE
built-in browser doesn't render pages for testi.at

### ISSUE THREAD

**Issue by vesper8** [beyondcode/helo-community#5]
I clicked on the 'testing' tab not understanding what this is, or who testi.at is and what their product is. So I clicked on the links "News", "Pricing" and while the left nav was displaying, the rest of the content was just blank

And by the way, I still don't understand what their service is.. it would be helpful if you said a few words about them and how their service can complement HELO

**Comment by sschlein** [comment]
They render your email in real email clients to check how they look there. So if you want to test the design of your email in Outlook 2003 or some other strange email client, you can do that with their service.

I agree that we should make that more clear and even add a setting to completely disable this tab if you don't use it.

**Comment by sschlein** [comment]
https://beyondco.de/docs/helo/basic-usage/mailboxes#testing
