### ISSUE TITLE
Add option to disable spam checks

### ISSUE THREAD

**Issue by codegefluester** [beyondcode/helo-community#50]
I've been testing out a new email for my project this morning which involved sending a handful of test emails over a short period of time. Every now and then I would see the following message in the "Spam" tab:

```
ADMINISTRATOR NOTICE: The query to URIBL was blocked. See http://wiki.apache.org/spamassassin/DnsBlocklists#dnsbl-block for more information. [URIs: <MY_DOMAIN>]
-0.0
```

I assume that this means that the results of said queries aren't cached and if you test too much (too fast), you'll find yourself blocked by the provider. Any chance we can either have a setting to turn those queries off completely OR have HELO cache the results for, say a few hours or something like that? I doubt that the blocklist status of a domain would change that quick for the blocklist having to be queried in real-time?

Closing this report with a thank you for this handy piece of kit, really loving the ease of use!

**Comment by sschlein** [comment]
I thought we already have an option to disable spam checks but wasn't able to find it myself. I'm adding this to the short term feature list and changing the title of this issue :)

**Comment by mechelon** [comment]
Will be added in the next release.
