### ISSUE TITLE
SMTP server does not close when the application does

### ISSUE THREAD

**Issue by stubbo** [beyondcode/helo-community#52]
When I first start up helo the smtp server starts up fine, however if i close it and try reopening it cant start the server because the previous server is still running.

I have found that i can stop the old one by opening task manager and closing all helo processes that popup.

**Comment by JackGamesFTW** [comment]
I am also having this issue.

I am on windows. It would be nice if it goes into the system tray.

**Comment by sschlein** [comment]
1.3.2 the server is properly killed on application close

**Comment by stubbo** [comment]
Seems to be working as expected now, thanks
