### ISSUE TITLE
Error opening the dmg

### ISSUE THREAD

**Issue by marijnbent** [beyondcode/helo-community#53]
<img width="285" alt="Screenshot 2020-12-22 at 15 03 53" src="https://user-images.githubusercontent.com/11903095/102896581-eab4c300-4466-11eb-8780-2598614f38ae.png">

Getting the following error when opening the .dmg on a Macbook Pro Apple Silicon.

**Comment by sschlein** [comment]
Our M1 MacBook is delayed and is going to arrive in the first week of January. I'm afraid that we can't check this earlier :-(

**Comment by sschlein** [comment]
I just tested this on a brand new M1 based Macbook pro and do not have the issue. Do you still experience it? If yes, please re-open the issue, thanks.
