### ISSUE TITLE
AppImage Icon Missing

### ISSUE THREAD

**Issue by dqfan2012** [beyondcode/helo-community#56]
The AppImage icon for Helo isn't showing up in Linux for me. My OS is Pop!_OS 20.04. Pop!_OS is based on Ubuntu (it's more or less a software package built on top of Ubuntu). I think that if the AppImage icons aren't working in Ubuntu, fixing it for Ubuntu will also fix it for Pop!_OS.

To help, I could create a few Ubuntu VMs (18.04, 20.04, & 20.10) to see if the AppImage icon is missing in any of those and report back here to let you know.

**Comment by MohammadAbusaleh** [comment]
I can confirm it doesn't work on Ubuntu for me too.

Difference between Tinkerwell and Helo

![image](https://user-images.githubusercontent.com/12821490/112223757-c2925700-8c43-11eb-8854-05ad1152d1db.png)

**Comment by mechelon** [comment]
Thank you for pointing this out. The bug will be fixed in the next release.
