### ISSUE TITLE
Make email server respond to client with errors

### ISSUE THREAD

**Issue by nm777** [beyondcode/helo-community#57]
I really love HELO! Thanks so much for a great product!

I realize that you may get a lot of suggestions or complaints. I also realize that my suggestion may be outside of the scope of what you want HELO to do. Still, here is what I'd love to see if it's not too difficult to implement.

I am currently debugging a worker process that sends emails. It handles email server errors in different ways. For example:

- If there is a connection issue, I'd probably wait and retry a few minutes later.
- If the server responds that the mailbox is full, I might choose to wait 24 hours and try again.
- If the server responds that the email address does not exist, I'll stop trying.

My suggestion is to add a way to set the response that HELO gives the SMTP client (the app currently being debugged) when it attempts to send an email. This could go under settings or in a separate page.

The UI would need a way to toggle the feature, a way to set when in the SMTP handshake the error occurs, and the message returned to the client. Maybe something like this?

![image](https://user-images.githubusercontent.com/19784999/113576406-22deac80-95e5-11eb-91e5-197c2663aedd.png)

Whether you add it or not, I'll still be a customer! Thanks!

**Comment by mechelon** [comment]
@nm777 I am not sure if I understand you correctly 🤔 We have a log output when forwarding a mail out of HELO (which is the only way to send an email from there as far as I know). Maybe this already helps you?

<img width="930" alt="CleanShot 2021-04-14 at 13 38 49@2x" src="https://user-images.githubusercontent.com/26432041/114704552-05b58680-9d27-11eb-8d26-323bd72c1b68.png">

**Comment by nm777** [comment]
Thanks for looking at this @mechelon. Let me see if I can try to explain.

HELO is acting as an email server, listening on port 2525. My app is the client that is sending email. In real life email servers sometimes don't accept email or have problems. When that happens, the app needs to detect this and do some error handling.

[Wikipedia](https://en.wikipedia.org/wiki/List_of_SMTP_server_return_codes#Example) has a couple of examples of the SMTP conversation between client and server if you're not familiar with how the protocol works. 

My suggestion above is to allow HELO to simulate a failing email server by returning an error status code and message during one of the SMTP protocol steps.

For example, after the app sends it's `RCPT TO:<theboss@example.com>` message instead of HELO's email service responding `250 Ok`, it could be configured to respond `450 Mailbox not found`. This would allow me to test how my app behaves when a mail server tells me that an email address is invalid.

I realize that you may be using a library that does not give you this level of control, but I thought I would at least see if it was possible as I figured if it's useful to me it may be useful to someone else as well.

I hope this helps.

**Comment by mechelon** [comment]
Thank you for your explanation! Makes this much more clear now. Even this is a fascinating approach I'm afraid this is beyond the scope of HELO.
