### ISSUE TITLE
Windows notification app name wrong

### ISSUE THREAD

**Issue by mmachatschek** [beyondcode/helo-community#58]
Hi, I noticed that the app name in the Windows notifications is displayed incorrectly. There is no issue with this but just a visual thing.

`electron.app.HELO` should be `HELO`

![image](https://user-images.githubusercontent.com/10237069/114581117-be27ef80-9c7f-11eb-893a-11fd610b217e.png)

**Comment by mechelon** [comment]
Thank you for pointing this out. The bug will be fixed in the next release.
