### ISSUE TITLE
Sharing emails not working

### ISSUE THREAD

**Issue by DanielFatkic** [beyondcode/helo-community#59]
When I try to share an email, I'm getting a "Something went wrong while sharing your email." notification without any further information about the issue.

Is there a way to see what went wrong? Are there any debug information / logs available somewhere?

**Comment by mechelon** [comment]
We don't have a log for sharing the mails, just for the forwarding through HELO. Could you forward the mail that failed to share to support@beyondco.de? Maybe there's some validation failing, but it's difficult to retrace without the mail. Thank you!

**Comment by DanielFatkic** [comment]
Thanks, I have forwarded it straight out from HELO. I hope it worked.

**Comment by mechelon** [comment]
That's a good suggestion - we will put this onto our internal roadmap.

I'm afraid we didn't received any e-mail from; did you save the log output for the forwarding or could you try it again to do so?

**Comment by mechelon** [comment]
We didn't received any e-mail so far. If this problem still exists, feel free to reopen the issue.
