### ISSUE TITLE
Heimdal Thor blocks the HELO Download

### ISSUE THREAD

**Issue by enigmatic-user** [beyondcode/helo-community#6]
I just purchased HELO and now wanted to download it from the licensing backend. When I clicked on the download link that leads to digitaloceanspaces.com, Firefox warned me about the SSL (or rather TLS) certificate:

> SSL_ERROR_BAD_CERT_DOMAIN

I manually changed the HTTPS URL to an HTTP URL, which seemed to work, but then [Heimdal Thor](https://heimdalsecurity.com/en/products/thor-premium-home) (a security software) blocked the page:

> Heimdal Security has blocked this page.
> 
> The web location you are trying to access may trigger phishing attempts or contain malicious content which could affect your system.

Maybe you'd like to contact them and convince them to unblock the site - or you could find a different hoster with a better reputation for your software.

I temporarily whitelisted the Site, downloaded the file and checked it using the virustotal.com service, so everything's fine for me personally, but it's not a very good first impression for first-time users who might not yet have built some trust in you (which I have, as a satisfied user of Tinkerwell 😉)...

**Comment by sschlein** [comment]
Hey, this might be related to an issue at our provider (Digital Ocean) this night. Can you check if this is still the case?

You are the only one reporting this issue so far so I hope it was temporary :)

**Comment by enigmatic-user** [comment]
Okay, the download seems to work now. But Heimdal Thor still seems to interfere with the "Check for updates" functionality. It works when I whitelist helo.fra1.digitaloceanspaces.com and shows an error message when I don't.

Thor is not a very widespread security solution yet, but a quite good one. If digitaloceanspaces.com is clean, they will certainly unblock it - just contact them if you care about this nuisance.
