### ISSUE TITLE
Attachments not opening

### ISSUE THREAD

**Issue by voicecode-bv** [beyondcode/helo-community#60]
When sending an email with one or more attachments (pdf files) the "open" link doesn't work. The save button does.

```
TypeError: f.openItem is not a function at openAttachment (app.b42785ef.js:1)
```

Using v1.5.0

**Comment by nm777** [comment]
I see the same issue.

I'm clicking the "open" link on an attachment: 
![image](https://user-images.githubusercontent.com/19784999/122598906-1b9b3c80-d033-11eb-9953-08209214c858.png)

I get no error message and the attachment doesn't open. Clicking "save" does allow me to save, then open the attachment.
If I open the Chrome developer tools, I can see the following error in the console:
```
chunk-vendors.cf7b3a27.js:99                              TypeError: f.openItem is not a function
    at openAttachment (app.b42785ef.js:1)
    at click (app.b42785ef.js:1)
    at at (chunk-vendors.cf7b3a27.js:99)
    at HTMLAnchorElement.n (chunk-vendors.cf7b3a27.js:99)
    at HTMLAnchorElement.Zr.i._wrapper (chunk-vendors.cf7b3a27.js:99)
```

Inspecting the code and jumping to the failing line I can see that the failure occurs on the `f.openItem(e.storedFilename)` call:
```javascript
// ...
methods: {
    // ...
    openAttachment(e) {
        f.openItem(e.storedFilename)
        // ^^^^^^^ This is what is failing
    },
// ...
```

If I set a breakpoint and use the javascript console I can get the attachment to open by typing `f.openPath(e.storedFilename)` in the console instead of `f.openItem(e.storedFilename)`.

I'm running macOS Big Sur v11.4 and using v1.5.0 of HELO.

I hope this helps.

Nate

**Comment by enigmatic-user** [comment]
Same issue with HELO 1.5.0 on a Windows 10 (version 21H1) machine.

**Comment by ultimateBusiness** [comment]
When we can have a fixed version, please?

**Comment by mechelon** [comment]
Thank you all for pointing this out. The bug will be fixed in the next release.

**Comment by voicecode-bv** [comment]
@mechelon great, can you give a timeframe about when to expect the next release? I've reported this issue like 4 months ago.
