### ISSUE TITLE
Error in Windows when trying to exit the application (through the menu)

### ISSUE THREAD

**Issue by AndresReyesDev** [beyondcode/helo-community#62]
Hello!

When I try to exit the application through the menu it shows the following error:

![image](https://user-images.githubusercontent.com/5054870/123841181-401dd100-d8dd-11eb-8b4a-da97e5168647.png)

This happens on Windows 10 and also on Windows 11 (which I installed yesterday).  In this case, the application is closed and does not remain in the background.

In addition, closing the application with X or Alt+F4 does not close the application (same as the bug previously reported by another user) leaving the application in the background and allowing several instances of it.

![image](https://user-images.githubusercontent.com/5054870/123841479-9ab72d00-d8dd-11eb-99cd-c55fb077a90f.png)

**Comment by mechelon** [comment]
Thank you for pointing this out. The bug should be fixed in the next release, feel free to reopen if it's not.
