### ISSUE TITLE
Unable to quit using ctrl + q or HELO -> quit

### ISSUE THREAD

**Issue by kaptk2** [beyondcode/helo-community#65]
When trying to quit the HELO app using the menu or the shortcut an error occurs.

![image](https://user-images.githubusercontent.com/466052/130136505-bd8f5a41-08ed-43cd-85ba-b72602076809.png)

Environment:

- HELO-1.5.0
- Ubuntu 20.04.2 LTS

To reproduce:
Open the HELO application, then try to quit the app using the menu or hotkey. The "x" button closes the app successfully.

**Comment by mechelon** [comment]
Thank you for pointing this out. The bug should be fixed in the next release, feel free to reopen if it's not.
