### ISSUE TITLE
Question: Can this be used with an staging server?

### ISSUE THREAD

**Issue by SudoGetBeer** [beyondcode/helo-community#7]
Hi,
 
first of all really like the product idea and everything.

So I understand how I can use this in an local environment but is there a way to connect this to our staging server? Maybe using the remote mailbox?

Maybe somebody already got an idea?

**Comment by sschlein** [comment]
Hey,

What do you mean with "connect"?

With the remote mailbox, you get a unique email address that can receive external emails. So if you register with this unique address on your staging environment, you get this email in your local HELO app. If this is your scenario, you can do this =)

Please keep in mind that we only store emails for 5 minutes in the remove mailbox so you should have your local application running to get it. You can find more information on remote mailboxes here: https://docs.beyondco.de/helo/1.0/basic-usage/remote-mailboxes.html

Please let me know if this answers your question.

**Comment by SudoGetBeer** [comment]
@sschlein Thanks for the fast answer.

Hm yes and on. I thought maybe It is possible to connect the remote server with the app. So i can catch all mails when used.

Schönen Tag noch 😉
