### ISSUE TITLE
Would be nice to automatically open attachments

### ISSUE THREAD

**Issue by reed-jones** [beyondcode/helo-community#9]
Instead of saving -> opening finder -> clicking on it to open -> viewing it -> deleting it, it would be really nice to be able to just 'open' the attachment

**Comment by euneuber** [comment]
At maximum, make it a configuration setting: auto-open yes/no

I send PDFs in sizes from 15kB to 2MB an HELO is without auto-open very slow...

**Comment by mpociot** [comment]
Version 1.1.0 fixes this, it now allows you to choose whether you want to save or open an attachment.
